# Chapter 2: Linearity 

In [1]:
# Linear regression with SciPy
"""
CAPM : Expected Return = risk-free + beta(Expected market return - risk-free)
"""
from scipy import stats 

stock_returns = [0.065, 0.0265, -0.0593, -0.001, 0.0346]
mkt_returns = [0.055, -0.09, -0.041, 0.045, 0.022]
b, a, r, p, std = stats.linregress(stock_returns, mkt_returns)

In [2]:
print(b, a)

0.5077431878770808 -0.008481900352462384


In [16]:
# Least squares regression with statsmodels 
import numpy as np
import statsmodels.api as sm 

num_periods = 9
all_values = np.array([np.random.random(8) for i in range(num_periods)])

y_values = all_values[:, 0]
x_values = all_values[:, 1:]
x_values = sm.add_constant(x_values)
results = sm.OLS(y_values, x_values).fit()

In [17]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  0.993
Method:                 Least Squares   F-statistic:                     159.0
Date:                Fri, 21 Aug 2020   Prob (F-statistic):             0.0624
Time:                        20:10:10   Log-Likelihood:                 78.529
No. Observations:                  21   AIC:                            -117.1
Df Residuals:                       1   BIC:                            -96.17
Df Model:                          19                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5697      0.111      5.145      0.1

In [7]:
print(results.params)

[ 0.75515538 -0.41330291  0.02407637 -0.69741638  0.7324195  -0.61060166
  0.28553685  0.18547097]


In [29]:
# Simple Linear optimization problem with 2 variables using Pulp
import pulp

x = pulp.LpVariable('x', lowBound=0)
y = pulp.LpVariable('y', lowBound=0)
problem = pulp.LpProblem(
            'A_simple_maximization_objective',
             pulp.LpMaximize)
problem += 3*x + 2*y, 'The objective function'
problem += 2*x + y <=100, '1st constraint'
problem += x + y <= 80, '2nd constraint'
problem += x <= 20, '3rd constraint'
problem.solve()

1

In [30]:
print('Maximization Results:')
for variable in problem.variables():
    print(variable.name,'=', variable.varValue)

Maximization Results:
x = 20.0
y = 60.0


In [32]:
# Example of implementing an integer programming model with binary conditions 
import pulp

dealers = ['X', 'Y', 'Z']
variable_costs = {'X': 500, 'Y': 350, 'Z': 450}
fixed_costs = {'X': 4000, 'Y': 2000, 'Z': 6000}

# Define PuLP variables to solve 
quantities = pulp.LpVariable.dicts('quantity', dealers, lowBound=0, cat=pulp.LpInteger)
is_orders = pulp.LpVariable.dicts('orders', dealers, cat=pulp.LpBinary)

#Initialize the model with constraints
model = pulp.LpProblem('A_cost_minimization_problem', pulp.LpMinimize)

model += sum([variable_costs[i]*quantities[i] + \
                  fixed_costs[i]*is_orders[i] for i in dealers]), 'Minimize portfolio cost'
model += sum([quantities[i] for i in dealers]) == 150, 'Total contracts required'
model += is_orders['X']*30 <= quantities['X'] <= is_orders['X']*100, 'Boundary of total volume of X'
model += is_orders['Y']*30 <= quantities['Y'] <= is_orders['Y']*90, 'Boundary of total volume of Y'
model += is_orders['Z']*30 <= quantities['Z'] <= is_orders['Z']*70, 'Boundary of total volume of Z'

model.solve()

1

In [33]:
print('Minimization Results:')
for variable in model.variables():
    print(variable, '=', variable.varValue)
print('Total cost:', pulp.value(model.objective))

Minimization Results:
orders_X = 0.0
orders_Y = 1.0
orders_Z = 1.0
quantity_X = 0.0
quantity_Y = 90.0
quantity_Z = 60.0
Total cost: 66500.0


In [52]:
%%timeit
#Using Numpy lingalg 
import numpy as np 

A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]])
B = np.array([4, 5, 6])

results = np.linalg.solve(A, B)

22.1 µs ± 944 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [56]:
%%timeit
#Lu Decomposition with SciPy
import numpy as np
import scipy.linalg as linalg

#Define A and B
A = np.array([
    [2., 1., 1.],
    [1., 3., 2.],
    [1., 0., 0.]])
B = np.array([4., 5., 6.])

LU = linalg.lu_factor(A)
x = linalg.lu_solve(LU, B)

28 µs ± 673 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [41]:
print(x)

[  6.  15. -23.]


In [44]:
P, L, U = linalg.lu(A)

print('P=', P)

print('L=', L)

print('U=', U)

P= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L= [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]
U= [[ 2.   1.   1. ]
 [ 0.   2.5  1.5]
 [ 0.   0.  -0.2]]


In [45]:
# Cholesky decomposition with NumPy
import numpy as np

A = np.array([
    [10., -1., 2., 0.],
    [-1., 11., -1., 3.],
    [2., -1., 10., -1.],
    [0., 3., -1., 8.]
])
B = np.array([6., 25., -11., 15.])

L = np.linalg.cholesky(A)

In [46]:
print(L)

[[ 3.16227766  0.          0.          0.        ]
 [-0.31622777  3.3015148   0.          0.        ]
 [ 0.63245553 -0.24231301  3.08889696  0.        ]
 [ 0.          0.9086738  -0.25245792  2.6665665 ]]


In [47]:
print(np.dot(L, L.T.conj()))

[[10. -1.  2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]]


In [48]:
y = np.linalg.solve(L, B) # L.L*.x=B; When L*.x=y, then L.y=B
x = np.linalg.solve(L.T.conj(), y) # x=L*'.y

In [50]:
print(x)

[ 1.  2. -1.  1.]


In [64]:

# QR decomposition with scipy

A = np.array([
    [2., 1., 1.],
    [1., 3., 2.],
    [1., 0., 0.]])
B = np.array([4., 5., 6.])

Q, R = linalg.qr(A) # QR decomposition
y = np.dot(Q.T, B) # Let y=Q'.B
x = linalg.solve(R, y) # solve Rx=y

In [65]:
print(x)

[  6.  15. -23.]


In [66]:
print(Q)

[[-0.81649658  0.27602622 -0.50709255]
 [-0.40824829 -0.89708523  0.16903085]
 [-0.40824829  0.34503278  0.84515425]]


In [67]:
print(R)

[[-2.44948974 -2.04124145 -1.63299316]
 [ 0.         -2.41522946 -1.51814423]
 [ 0.          0.         -0.16903085]]


In [68]:
print(np.dot(Q, R))

[[ 2.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00 -2.42598438e-17 -2.10832838e-16]]


In [73]:
# The Jacobi method 
import numpy as np

def jacobi(A, B, n, tol=1e-10):
    x = np.zeros_like(B)
    
    for iter_count in range(n):
        x_new = np.zeros_like(x)

        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x[:i])
 
            s2 = np.dot(A[i, i + 1:], x[i + 1:])

            x_new[i] = (B[i] - s1 - s2) / A[i, i]
   
        if np.allclose(x, x_new, tol):
            break
        x = x_new
    return x

In [77]:
A = np.array([
    [10., -1., 2., 0.],
    [-1., 11., -1., 3.],
    [2., -1., 10., -1.],
    [0., 3., -1., 8.]
])
B = np.array([6., 25., -11., 15.])
n = 25

x = jacobi(A, B, n)
print('x =', x)

x = [ 1.  2. -1.  1.]


In [84]:
#Using the Gauss-Seidel method
import numpy as np

def gauss(A, B, n, tol=1e-10):
    L = np.tril(A) #Returns the lower traingular matrix of A
    U = A - L # Decompose A = L + U
    L_inv = np.linalg.inv(L)
    x = np.zeros_like(B)
    
    for i in range(n):
        Ux = np.dot(U, x)
        x_new = np.dot(L_inv, B - Ux)
        
        if np.allclose(x, x_new, tol):
            break
        
        x = x_new
        
    return x

In [85]:
A = np.array([
    [10., -1., 2., 0.],
    [-1., 11., -1., 3.],
    [2., -1., 10., -1.],
    [0., 3., -1., 8.]
])
B = np.array([6., 25., -11., 15.])
n = 25

x = gauss(A, B, n)
print('x =', x)

x = [ 1.  2. -1.  1.]
